name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Vite Github Pages Deployer
      uses: skywarth/vite-github-pages-deployer@v1.2.0
      with:
        # Public base path string for vite, this affects the routing, history and asset links. Make sure to provide appropriately since Github Pages stores your app in a directory under a subdomain.
        public_base_path: /
        build_path: ./dist
        install_phase_node_env: development
        build_phase_node_env: prodduction
        package_manager: npm
        artifact_name: static
        debug_mode: false
